### ISSUE TITLE
[OTHER] Mudar sistema de exibição dos componentes

### ISSUE THREAD

**Issue by apfzvd** [b2wads/grimorio-ui#111]
Hoje o storybook não atende tanto as nossas expectativas de documentação de componentes. Não é complicado de exibir os props e fornecer código boilerplate como é difícil o deploy dos arquivos estáticos.

Essa issue é para que a gente faz um benchmark entre as soluções existentes e decida se vamos continuar com storybook ou outra solução.

## Características dessa ferramenta

- [ ] Poder gerar traduções de uma língua principal
- [x] Poder gerar estáticos finais que podemos servir de forma simples
- [x] Facilidade de escrever documentação e inserir code snippets

**Comment by lucasdomi** [comment]
Achei um artigo que levanta os principais concorrente pro storybook e explica um pouco como eles funcionam.

https://blog.logrocket.com/alternatives-to-react-storybook/

**Comment by apfzvd** [comment]
> Achei um artigo que levanta os principais concorrente pro storybook e explica um pouco como eles funcionam.

Boa! Acho uma boa geral ler e a gente trocar figurinhas depois! :)

**Comment by apfzvd** [comment]
Por enquanto, atualização do storybook tem se mostrado suficiente! Caso precisemos de algo a mais no futuro, reabro a issue!
