### ISSUE TITLE
[OTHER] Remover o componente tableFixed

### ISSUE THREAD

**Issue by dehmirandac2** [b2wads/grimorio-ui#146]
A gente tinha um componente de tableFixed, que era para fixar algumas colunas da tabela. O componente era feito por duas tabelas, lado a lado, sendo a da esquerda fixa e a da direita com scroll.
Porém, precisávamos fazer hover na linha dessa tableFixed, mas começou a ficar muito complexo disparar o hover nas duas tabelas.
Sendo assim, no próprio componente Table, adicionei uma props, para que possamos dizer quantas colunas devem ficar fixas. Assim, o valor de cada coluna fixa é calculado e adicionamos a elas uma posição sticky.

Por fim, a dúvida é: se agora temos a possibilidade de usar coluna fixa no próprio componente Table, precisamos manter o componente tableFixed?

@apfzvd @lucasdomi

**Comment by apfzvd** [comment]
Absolutamente concordo! Por mim pode meter a tesoura nele.
Aliás, ficou muito muito irado essa feature no Table! :star_struck:  :star_struck: :star_struck:

**Comment by dehmirandac2** [comment]
> Absolutamente concordo! Por mim pode meter a tesoura nele.
> Aliás, ficou muito muito irado essa feature no Table!

Uhuul! Valeus :heart: 
Qualquer sugestão de melhoria, pode falar
