### ISSUE TITLE
[BUG] Problema com dependência não instalada

### ISSUE THREAD

**Issue by dehmirandac2** [b2wads/grimorio-ui#149]
**Descreva o bug**
Quando fomos usar o Grimório no nosso projeto, reparamos que começou a dar um problema de falta de dependência, no componente de buttonUpload. O erro é: regeneratorRuntime is not defined

O que fizemos, para resolver temporariamente, foi adicionar o pacote regenerator-runtime no nosso projeto e importá-lo no app.js. Mas imagino que não seja o melhor jeito, exigir que o projeto que vai usar o Grimório tenha que instalar essa dependencia

Ainda não fiz qualquer tipo de investigação a fundo, mas imagino que essa dependência não tenha que estar como dev dependecies no Grimório.

**Screenshots**
![runtime](https://user-images.githubusercontent.com/8313529/82679713-adaef680-9c21-11ea-9721-d96871ac8c43.png)

**Comment by apfzvd** [comment]
@dehmirandac2 Eu tinha visto esse erro quando tava escrevendo os testes! Acabei implementando o ajuste só nas configs do babel de teste porque pensei que era um problema só no jest.

Fiz um PR inserindo nas configs do babel de prod tb. Depois vou testar gerar um pacote localmente aqui e ver se resolve mesmo :D

**Comment by dehmirandac2** [comment]
> @dehmirandac2 Eu tinha visto esse erro quando tava escrevendo os testes! Acabei implementando o ajuste só nas configs do babel de teste porque pensei que era um problema só no jest.
> 
> Fiz um PR inserindo nas configs do babel de prod tb. Depois vou testar gerar um pacote localmente aqui e ver se resolve mesmo :D

Opaa, maravilha! :tada:
