### ISSUE TITLE
[DISCUSSION] Menu, Accordion e Sidebar; E o Header também

### ISSUE THREAD

**Issue by apfzvd** [b2wads/grimorio-ui#158]
Hoje esses três componentes estão super misturados, com estilos em lugares que, na minha opinião, só deixa a manutenção mais complexa. 

_Exemplo: O estilo para a aplicação do accordion no sidebar está no stylus do accordion. Caso queira mudar um detalhe na sidebar, é preciso mexer nos arquivos do accordion - o que me parece um pouco contra-intuitivo._

Por isso tenho algumas perguntas pra gente discutir:
- Menu é um componente necessário? Ele funciona do jeito que está implementado? 
- Accordion é um componente necessário? Ele funciona do jeito que está implementado?
- Sidebar é um componente que faz sentido do jeito que foi implementado?
- Header é um componente que faz sentido? Qual é a vantagem que ele trás?

**Comment by dehmirandac2** [comment]
> Hoje esses três componentes estão super misturados, com estilos em lugares que, na minha opinião, só deixa a manutenção mais complexa.
> 
> _Exemplo: O estilo para a aplicação do accordion no sidebar está no stylus do accordion. Caso queira mudar um detalhe na sidebar, é preciso mexer nos arquivos do accordion - o que me parece um pouco contra-intuitivo._
> 
> Por isso tenho algumas perguntas pra gente discutir:
> 
> * Menu é um componente necessário? Ele funciona do jeito que está implementado?
> * Accordion é um componente necessário? Ele funciona do jeito que está implementado?
> * Sidebar é um componente que faz sentido do jeito que foi implementado?
> * Header é um componente que faz sentido? Qual é a vantagem que ele trás?

- Menu: Acho que não é tão útil assim. De uma maneira geral, ele serve pra ter um ícone com um texto ao lado.
- Accordion: De uma maneira geral, só usamos dentro do menu.
- Sidebar: Pra mim, o que esse componente tem de mais útil é a opção de abrir e fechar. Acho isso chatinho de fazer, então já ter algo pronto ajuda. Além de já estar preparo pra funcionar mobile;
- Header: acho que a única vantagem é essa a versão pra desktop e pra mobile. De resto, acaba que acho que não precisaria de muitas coisas nele, tipo o componente de usuário

Qual a sua opinião sobre esses componentes, @apfzvd?

**Comment by apfzvd** [comment]
> - Menu: Acho que não é tão útil assim. De uma maneira geral, ele serve pra ter um ícone com um texto ao lado.

Concordo que ele não serve de muita coisa! Sou a favor lançar a tesoura :scissors: nele;

> - Accordion: De uma maneira geral, só usamos dentro do menu.

Eu gosto da ideia de um Accordion, mas acho o jeito que está feito hoje um pouco "complexo". O `AccordionTitle` e o `AccordionContent` porderiam virar um só componente `AccordionPanel`, que teria uma prop title e o children seria o content. Acho que a complexidade ajuda no fato da gente não usar.

> - Sidebar: Pra mim, o que esse componente tem de mais útil é a opção de abrir e fechar. Acho isso chatinho de fazer, então já ter algo pronto ajuda. Além de já estar preparo pra funcionar mobile;

Com relação a Sidebar, eu acho super prático ele já abrir e fechar e estar pronto pro mobile, também! Eu acho que a gente pode deixar ele "melhor", integrando de vez o accordion nele (e o menu também, nas no caso acabando com o componente menu), sem ter que importar os dois quando a gente vai fazer o uso do sidebar no projeto.

> - Header: acho que a única vantagem é essa a versão pra desktop e pra mobile. De resto, acaba que acho que não precisaria de muitas coisas nele, tipo o componente de usuário

Pois é, acaba que ele é um retângulo que mostra uma logo na versão mobile, haha. Concordo que muitas props ainda tem a cara do afiliados. Por mais estranho que pareça, eu acho que a única vantagem desse componente é unidade visual (tamanho, cor, font-size) e ficaria melhor perdendo esses detalhes de user, items e logout.

Que acham?

**Comment by dehmirandac2** [comment]
> > * Menu: Acho que não é tão útil assim. De uma maneira geral, ele serve pra ter um ícone com um texto ao lado.
> 
> Concordo que ele não serve de muita coisa! Sou a favor lançar a tesoura  nele;
> 
Lansa a braba! :scissors: 
> > * Accordion: De uma maneira geral, só usamos dentro do menu.
> 
> Eu gosto da ideia de um Accordion, mas acho o jeito que está feito hoje um pouco "complexo". O `AccordionTitle` e o `AccordionContent` porderiam virar um só componente `AccordionPanel`, que teria uma prop title e o children seria o content. Acho que a complexidade ajuda no fato da gente não usar.
> 
Acho ótimo simplificar esse componente! Por mim, podemos seguir assim
> > * Sidebar: Pra mim, o que esse componente tem de mais útil é a opção de abrir e fechar. Acho isso chatinho de fazer, então já ter algo pronto ajuda. Além de já estar preparo pra funcionar mobile;
> 
> Com relação a Sidebar, eu acho super prático ele já abrir e fechar e estar pronto pro mobile, também! Eu acho que a gente pode deixar ele "melhor", integrando de vez o accordion nele (e o menu também, nas no caso acabando com o componente menu), sem ter que importar os dois quando a gente vai fazer o uso do sidebar no projeto.
> 
Total! Eu achava que a gente nem usava o accordion e o menu, mas vi que a gente importa junto com o sidebar! Se for integrado, melhor ainda
> > * Header: acho que a única vantagem é essa a versão pra desktop e pra mobile. De resto, acaba que acho que não precisaria de muitas coisas nele, tipo o componente de usuário
> 
> Pois é, acaba que ele é um retângulo que mostra uma logo na versão mobile, haha. Concordo que muitas props ainda tem a cara do afiliados. Por mais estranho que pareça, eu acho que a única vantagem desse componente é unidade visual (tamanho, cor, font-size) e ficaria melhor perdendo esses detalhes de user, items e logout.
> 
Siiim! Concordo. Acho que vale mexer pra deixar mais simples
> Que acham?
Se quiser criar issues pra essas partes, podemos dividir essas alterações!

**Comment by apfzvd** [comment]
Fechando essa issue pois o Header, Menu e Sidebar foram modificados. Vou abrir uma issue específica para o Accordion!
