### ISSUE TITLE
[OTHER] Traduzir para português documentações que fizemos em inglês

### ISSUE THREAD

**Issue by apfzvd** [b2wads/grimorio-ui#175]
Como discutido na issue #116, decidimos continuar e manter nossa documentação em português. Porém, existem algumas partes do projeto com documentação em inglês. Sugiro que a gente faça a tradução desses documentos para português!

Temos dois documentos atuais em inglês:

- [x] CSS Code style (/docs-src/css-code-style.md)
- [x] Contributing.md (/CONTRIBUTING.md)

Principalmente o contributing, seria importante deixar em português para facilitar o entendimento dos passos necessários para começar a contribuir com o projeto!

Caso alguém tenha visto mais alguma doc em inglês, só comentar que eu adiciono aqui na lista!

**Comment by JoaoVictorNascimento** [comment]
Eu faço a tradução

**Comment by LuizHAP** [comment]
Olá, vou fazer a tradução!

**Comment by LuizHAP** [comment]
Fiz a alteração da branch, para não dar problemas durante o merge. Poderia verificar @apfzvd ? Aproveitando, poderia verificar as alterações no projeto conforme o link (https://hacktoberfest.digitalocean.com/hacktoberfest-update) ? Obrigado!

**Comment by apfzvd** [comment]
> Fiz a alteração da branch, para não dar problemas durante o merge. Poderia verificar @apfzvd ? Aproveitando, poderia verificar as alterações no projeto conforme o link (https://hacktoberfest.digitalocean.com/hacktoberfest-update) ? Obrigado!

Oi @LuizHAP! Queria te agradecer pelo PR e pela lembrança de ajustar o repo para ficar de acordo com esses novos padrões do hacktoberfest :D Deixei algumas sugestões de mudança na tradução, mas achei que ficou ótimo num geral. Vou marcar seu PR como aceito no hacktoberfest de qualquer forma, okay? :)

**Comment by apfzvd** [comment]
> Eu faço a tradução

Oi @JoaoVictorNascimento! O @LuizHAP está cuidando da tradução do contributing, mas se quiser, pode tocar a tradução do css-code-style :D

**Comment by LuizHAP** [comment]
Obrigado @apfzvd vou revisar a PR essa noite e te retorno. Obrigado pela oportunidade!

**Comment by apfzvd** [comment]
> Obrigado @apfzvd vou revisar a PR essa noite e te retorno. Obrigado pela oportunidade!

Tamo junto! Se tiver qualquer dúvida sobre os comentários que deixamos lá, não hesite em perguntar! :D

**Comment by LuizHAP** [comment]
Pronto pessoal, revisei novamente, poderiam analisar? @apfzvd

**Comment by JoaoVictorNascimento** [comment]
Ok eu faço a tradução do css-code-style.md

**Comment by JoaoVictorNascimento** [comment]
@apfzvd subi o PR com a tradução do css-code-style, se puder ver depois e se aprovar lembra de colocar a label do hacktoberfest.

**Comment by dehmirandac2** [comment]
> @apfzvd subi o PR com a tradução do css-code-style, se puder ver depois e se aprovar lembra de colocar a label do hacktoberfest.

Ei João Victor, tudo bem? Obrigada por contribuir com nosso projeto. Ficou muito legal a tradução!
Fiz alguns comentários, mais de pequenos ajustes mesmo. Vou ver com a @apfzvd se ela tem mais alguma consideração a fazer.

De qualquer maneira, já adicionei a label da Hacktoberfest lá! :tada:

**Comment by apfzvd** [comment]
@LuizHAP sua PR está mergeada! Na próxima versão do grimório já vai estar valendo :star_struck: 

E @JoaoVictorNascimento, vi seu PR e concorco com os ajustes sugeridos pela @dehmirandac2! Obrigado, também, por contribuir com o nosso projeto! :D

**Comment by apfzvd** [comment]
Pessoal, PRs megeados! Muito obrigado a vocês dois @LuizHAP e @JoaoVictorNascimento por contribuirem! Se puderem dar aquela estrelinha no projeto depois, super ajuda ;) Bom hacktoberfest pra vocês! :rocket:

**Comment by LuizHAP** [comment]
Com certeza! Bom sucesso para vocês meninas, voeem longe! 🚀
