### ISSUE TITLE
Uso do Package Registry do Github

### ISSUE THREAD

**Issue by dehmirandac2** [b2wads/grimorio-ui#37]
Precisamos ver se é uma boa possibilidade usar o Registry.
Pontos importantes:

1 - Gerar um pacote para cada tema? (Afiliado e Ads)
2- Qual seria a dificuldade para usar o tema em desenvolvimento? Algo que ainda não foi publicado, mas precisa ser usado numa área de staging, por exemplo

**Comment by apfzvd** [comment]
Por enquanto, decidimos usar o pacote no NPM, porque o GH registry exige configuração a mais para a instalação. Os releases "em desenvolvimento" ainda serão usados de forma local.
