### ISSUE TITLE
Unificar pacotes

### ISSUE THREAD

**Issue by apfzvd** [b2wads/grimorio-ui#38]
Antes da gente fazer a issue #37 a gente precisa unificar, de alguma forma, as variantes do tema.

Pensei, a princípio, em gerar vários css, mas talvez existam outras formas melhoras. Acho uma boa a gente dar uma estudada!

- Documentar instalação do projeto
  - Documentar as variáveis
  - Documentar trecho do Webpack para juntar CSS
  - Documentar a existência de 2 css (custom e default)
 - Mostrar as duas formas de fazer a instalação (entry point no Webpack ou no Html)
- Documentar processo de build do Grimório

**Comment by PabloAlexandre** [comment]
@apfzvd eu já vi algumas libs de ui kit fazendo essa questão de gerar diversos css's e você na hora de usar um tema diferente só fazer a importação do que você quer:

```
import 'grimorio-ui/themes/main.css'
```

Dessa forma, os module bundlers conseguem resolver pra não carregar os estilos completos, acho que pode ser uma boa alternativa.

**Comment by dehmirandac2** [comment]
Vou deixar comentado aqui, caso a gente queira passar as configurações de variáveis pelo Javascript:

https://github.com/macropodhq/postcss-constants

Aqui como o Material faz:

https://material-ui.com/customization/color/#color-tool

**Comment by apfzvd** [comment]
Devidamente unificados. Olhar o [processo de build](https://github.com/b2wads/grimorio-ui/blob/master/docs/processo-de-build.md) para entender melhor como!
