### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by apfzvd** [b2wads/grimorio-ui#61]
Agora que estamos open source, seria legar ter uma logo! Pensei em algo como um chapéu de bruxa :thinking: O que acham?

Também pensei em usar [essa fonte](https://fonts.google.com/specimen/Paytone+One) (achei fofo):
E usar esse cor de referência: [#7934d0](https://mycolor.space/?hex=%237934D0&sub=1)

**Comment by dehmirandac2** [comment]
Pra ficar de referência:

https://www.behance.net/gallery/38506835/Dziorawy-Kociol?tracking_source=search%7Cmagic%20logo

**Comment by mandyellow** [comment]
Olá 🦊 fiz uma opção de logo para vocês! No exemplo abaixo coloquei uma versão colorida e uma versão com uma cor, só para vocês verem como fica. Sei que está um pouco diferente do que pediram, mas espero que gostem!

![image](https://user-images.githubusercontent.com/30158643/66240504-82fd4580-e705-11e9-8170-20e5d1ef8d4f.png)

**Comment by lucasdomi** [comment]
Muito bom! :tada: :tada: :tada: :tada:

**Comment by lucasdomi** [comment]
Se você quiser contribuir com o projeto, abre uma PR adicionando as duas logos na pasta images!

**Comment by apfzvd** [comment]
Muito legal! Todo mundo aqui curtiu! :raised_hands: Só fazer isso aí que o @lucasdomi disse :D

**Comment by daltonmatos** [comment]
Obrigado, @mandyellow :tada: :heart: :confetti_ball: :sparkle: :sparkles: :sparkling_heart:
