### ISSUE TITLE
Atualizar docs de instalação

### ISSUE THREAD

**Issue by apfzvd** [b2wads/grimorio-ui#70]
Hoje para instalar precisamos:

* Adicionar o grimorio as dependências:
```js
"dependencies": {
  "grimorio-ui": "./packages/grimorio-ui-x.x.x.variation.tgz"
}
```

* Importar o css no js principal;
```js
import '[node_modules path]/grimorio-ui/dist/grimorio-ui.min.css';
```
* Adicionar os seguintes css no webpack com os respectivos loaders:
```js
path.resolve(__dirname, '[node_modules path]/grimorio-ui/dist/'),
path.resolve(__dirname, '[node_modules path]/grimorio-ui/node_modules/react-dates/lib/css/_datepicker.css'),
```
* Fazer os passos necessários para exportar isso como arquivo .css;
  * No webpack <= 3.x.x, usando o `extract-text-webpack-plugin` é possível extrair um css proprio do tema, separado.
  * No webpack 4.x.x é preciso usar o `mini-css-extract-plugin` que não permite 2 instancias, juntando todo o css em um só (precisamos validar essa decisão)

**Comment by daltonmatos** [comment]
Maravilha @apfzvd !!

Depois temos que pensar o que podemos fazer para que a instalação do grimorio possa ser a mais simples e rápida possível. Mas isso podem ser outras issues. :tada:

**Comment by dehmirandac2** [comment]
@apfzvd Vocês já atualizou isso no Readme, certo?

**Comment by apfzvd** [comment]
Atualizei sim, haha. Vou fechar!
