### ISSUE TITLE
Deploy do storybook

### ISSUE THREAD

**Issue by apfzvd** [b2wads/grimorio-ui#72]
[O storybook permite ser deployado como um app estático](https://storybook.js.org/docs/basics/exporting-storybook/). 
Acho que seria super legal poder fazer um deploy e subir o storybook em algum lugar tanto para consulta do time de front quanto para que designers e outras pessoas possam ter fácil acesso a nossa biblitoteca e possam interagir com ela. 

O que acham? :rocket:

**Comment by PabloAlexandre** [comment]
@apfzvd acho que seria interessante. É bem simples colocar isso em uma hospedagem de estáticos também, praticamente sem custos. Se quiser posso abrir o PR dessa ideia hospedando no netlify, o que acha?

**Comment by apfzvd** [comment]
@PabloAlexandre Acho uma boa! Nunca usei o netlify, acho que seria uma boa pra ver como é também :)

**Comment by PabloAlexandre** [comment]
Então @apfzvd, temos um problema de incompatibilidade do webpack. 

Na teoria, gerar o build era só trocar o comando `start-storybook` para `build-storybook`. O problema é que na configuração do webpack do storybook, não é utilizado o `extract-text-webpack-plugin`, o que faz com que o css não seja exportado e não carregue no build. Utilizar a config do webpack de produção deveria resolver, só que tem um problema que o projeto utiliza a versão `3.5.2`, e o Storybook tem o seu próprio webpack com a versão `4.35.3`, o que dá incompatibilidade com o `extract-text-webpack-plugin`. Eles até recomendam migrar para o `mini-css-extract-plugin` quando você usa a versão 4 do webpack, só que ele por sua vez não tem compatibilidade com o webpack 3 haha. Isso não deveria ser um problema, só que o triste é que essa lib usa o webpack que tá declarado na versão do `package.json`, o que faz com que ela seja incompatível.

Eu pensei em duas soluções para contornar esse problema e queria ouvir opiniões:

1 - Hospedar num servidor tipo o now, onde a gente consegue definir o comando do storybook e deixar ele rodando. O ponto ruim é que não é muito flexível essa opção e não resolve de fato o problema, porém não precisaria mexer em nada de config.

2 - Fazer upgrade na versão do webpack e configurar o `mini-css-extract-plugin`. Assim conseguiriamos resolver de fato o problema, mas teria essa preocupação de validar que não quebrou nada tanto na hora do desenvolvimento quanto na hora do build.

O que acham? Alguma outra opção?
