### ISSUE TITLE
[BUG] Cor do Feedback de sucesso

### ISSUE THREAD

**Issue by dehmirandac2** [b2wads/grimorio-ui#99]
**Descreva o bug**
O componente Feedback está usando a cor primária para o sucesso. Isso é um problema, pois se a cor primária do projeto de quem for usar for roxo, todos os alertas de sucesso serão roxo.

Sendo assim, acredito que a cor de sucesso do Feedback deveria ser fixa. Um verde que a gente definisse

**Comment by apfzvd** [comment]
Acho que as cores de danger, warning e success poderiam ser definidade pelas variaveis css, que acha?
